baseURL = "https://onetwofoureight.com"
enableGitInfo = true
languageCode = "en-us"
theme = "hermit-v2"
title = "1248"

[menu]

[[menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[menu.main]]
name = "About"
url = "about/"
weight = 20

[params]
footerCopyright = ' <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
footerHideThemeName = true
gitUrl = "https://github.com/jamesbraza/onetwofoureight.com"
homeSubtitle = "and beyond!"
homeSubtitlePrinter = false
justifyContent = false
legacyLayout = true
readTime = false
relatedPosts = false
shareSocial = true

[params.author]
about = "about"
name = "James Braza"

[params.dateform]
LongDate = "Jan 2, 2006"
NumDateLong = "2006-01-02 15:04 -0700"
NumDateShort = "2006-01-02"
ShortDate = "Jan 2"

[[params.socialLinks]]
# SEE: https://github.com/Track3/hermit#social-icons
name = "github"
url = "https://github.com/jamesbraza/onetwofoureight.com"
