[tool.codespell]
check-filenames = true
check-hidden = true

[tool.pymarkdown]
extensions.front-matter.allow_blank_lines = true
extensions.front-matter.enabled = true
plugins.line-length.code_block_line_length = 88  # Match ruff line-length
plugins.line-length.enabled = true
plugins.line-length.line_length = 120  # Match ruff max-doc-length
plugins.line-length.stern = true
plugins.line-length.tables = false
plugins.no-duplicate-heading.siblings_only = true  # GitHub appends -X for duplicated headings
plugins.no-emphasis-as-heading.enabled = false
plugins.no-inline-html.enabled = false

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2  # Match Python PEP 8
spaces_indent_inline_array = 4  # Match Python PEP 8
trailing_comma_inline_array = true
